# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

- name: Create PDF and HTML
  # You may pin to the exact commit or the version.
  # uses: BaileyJM02/markdown-to-pdf@07e199be5d4a6a8952d5af819d9fabbbe521b2cd
  uses: BaileyJM02/markdown-to-pdf@v1.0.1
  with:
    # (Path) The location of the folder containing your .md or .markdown files
    input_dir: 
    # (Path) The location of the folder containing your images, this should be the route of all images
    images_dir: # optional
    # (String) The path you use to import your images that can be replaced with the server URL
    image_import: # optional
    # (Path) The location of the folder you want to place the built files
    output_dir: # optional
    # (Boolean) Whether to also create a .html file
    build_html: # optional
    # (File) The location of the CSS file you want to use as the theme
    theme: # optional
    # (File) The location of the CSS file you want to use as the code snipped highlight theme
    highlight_theme: # optional
    # (File) The location of the HTML/Mustache file you want to use as the HTML template
    template: # optional
